/**Copyright (C) 2013 Thomas Maher
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package com.jimsuplee.aircraftcarriers;

import android.app.Activity;
//import android.content.Context;
//import android.content.res.TypedArray;
import android.os.Bundle;
import android.view.View;
//import android.view.ViewGroup;
//import android.widget.AdapterView;
//import android.widget.AdapterView.OnItemClickListener;
//import android.widget.BaseAdapter;
//import android.widget.Gallery;
import android.widget.ImageView;
import android.widget.TextView;
//import android.widget.Toast;

public class Pictures extends Activity {

	// @Override
	// public void onCreate(Bundle savedInstanceState) {
	// super.onCreate(savedInstanceState);
	// setContentView(R.layout.activity_pictures);
	// }
	static int index = 0;
	String[] stringCarriers = {
			"uss_harry_s_truman_cvn75_in_drydock_2012",
			"ford",
			"liaoning",
			"kuznetsov",
			"queenelizabeth",
			"vikramaditya",
			"charlesdegaulle",
			"saopaulo",
			"america",
			"cavour",
			"juancarlos",
			"hyuga",
			"chakrinaruebet",
			"a12__cvn76.png",
			"a4ku_landing_on_carrier_sao_paulo_2003.png",
			"admiral_hipper_oni.png",
			"aircraft_carrier_sao_paulo_in_rio_122007.png",
			"aircraft_carriers_under_attack_at_kure_19_march_1945.png",
			"baku_dnsc9005958r.png",
			"baku_dnsn8906990c.png",
			"benmychree_iii_on_her_sea_trials.png",
			"bundesarchiv_bild_10207567_hamburg_brennende_europa_im_hafen.png",
			"bundesarchiv_bild_10210309_katapultflugzeug_des_dampfers_europa.png",
			"bundesarchiv_bild_134b0676_flugzeugtrager_graf_zeppelin.png",
			"bundesarchiv_rm_25_bild02_flugzeugtrager_graf_zeppelin_bau.png",
			"bundesarchiv_rm_25_bild64_flugzeugtrager_graf_zeppelin_bau.png",
			"carrier_shokaku.png",
			"cvn_73_gnangarra_02.png",
			"dmitry_medvedev_on_the_admiral_kuznetsov.png",
			"fig_of_japanese_aircraft_carrier_shoho_in_1942.png",
			"grafzeppelin1.png",
			"hms_benmychree_off_the_dardanelles.png",
			"hms_benmychree_underfire_11_january_1917.png",
			"hms_ocean_ifos2005_cropped.png",
			"hms_ocean_moored_in_greenwich_london_for_the_2012_olympic_games.png",
			"ijn_carrier_amagi_capsized_off_kure_in_1946.png",
			"indian_navy_flotilla_with_aircraft_carriers_vikramaditya_r33_and_viraat_r22.png",
			"ins_vikramaditya_in_baltic_sea.png",
			"ins_vikrant_cgi.png",
			"japanese_aircraft_carrier_kasagi_cropped.png",
			"japanese_aircraft_carrier_zuiho.png",
			"js_izumo_ddh183_just_after_her_launch.png",
			"juan_carlos_l61_in_istanbul.png",
			"katsuragi_awm_099798.png",
			"la_foudre.png",
			"la_foudre_tending_torpedo_boats_bf_1923.png",
			"launch_of_benmychree_iii_march_23rd_1908.png",
			"lhd_juan_carlos_i_in_malaga.png",
			"lowering_the_flag_on_zuikaku.png",
			"mikoyan_mig29k_of_the_indian_navy.png",
			"qe_class_carrier.png",
			"seydlitz_reconnaissance_photo.png",
			"shoho_g17026.png",
			"shoho_under_attack.png",
			"shokaku_prelaunch.png",
			"shokaku_santa_cruz_fire.png",
			"ss_europa_ss_paris_sank.png",
			"ss_liberte.png",
			"statelibqld_1_133753_benmycaree_ship.png",
			"stern_of_hms_benmychree.png",
			"tbf_georgebush.png",
			"torpedoe_boat_tender_foudre.png",
			"uss_gerald_r_ford_cvn78_in_dry_dock_front_view_2013.png",
			"uss_harry_s_truman_cvn75_in_drydock_2012.png",
			"uss_john_c_stennis_cvn74__hms_illustrious_r_06.png",
			"uss_reagan071030n6074y053.png",
			"ussronaldreaganbyphilkonstantin.png",
			"varyag_during_refitting.png",
			"vikramaditya_7.png",
			"vikrant.png",
			"zuiho1944.png",
			"zuikaku_at_cape_engano.png",
			"zuikaku_flight_deck.png",
			"zuikaku_november_1941.png",
			"uss_abraham_lincoln_cvn_72",
			"japanese_battlecruiser_amagi",
			"ara_independencia_1958",
			"ara_veinticinco_de_mayo_v2",
			"brazilian_aircraft_carrier_minas_gerais",
			"brazilian_aircraft_carrier_sao_paulo_a12",
			"chinese_aircraft_carrier_liaoning",
			"flugzeugtrager_b",
			"french_aircraft_carrier_arromanches_r95",
			"french_aircraft_carrier_bearn",
			"french_aircraft_carrier_bois_belleau",
			"french_aircraft_carrier_charles_de_gaulle_r91",
			"french_aircraft_carrier_charles_de_gaulle_r91",
			"french_aircraft_carrier_clemenceau_r98",
			"french_aircraft_carrier_dixmude",
			"french_aircraft_carrier_foch_r99",
			"french_aircraft_carrier_joffre",
			"french_aircraft_carrier_la_fayette_r96",
			"french_aircraft_carrier_painleve",
			"french_aircraft_carrier_verdun",
			"french_seaplane_carrier_commandant_teste",
			"french_seaplane_carrier_foudre",
			"french_submarine_surcouf",
			"german_aircraft_carrier_graf_zeppelin",
			"german_cruiser_seydlitz",
			"hmas_albatross_1928",
			"hmas_melbourne_r21",
			"hmas_sydney_r17",
			"hmas_vengeance_r71",
			"hmcs_bonaventure_cvl_22",
			"hmcs_magnificent_cvl21",
			"hmcs_warrior_r31",
			"hms_activity_d94",
			"hms_albion_r07",
			"hms_ameer_d01",
			"hms_arbiter_d31",
			"hms_archer_d78",
			"hms_argus_i49",
			"hms_ark_royal_1914",
			"hms_ark_royal_91",
			"hms_ark_royal_r07",
			"hms_ark_royal_r09",
			"hms_atheling_d51",
			"hms_attacker_d02",
			"hms_audacity_d10",
			"hms_avenger_d14",
			"hms_battler_d18",
			"hms_begum_d38",
			"hms_benmychree",
			"hms_biter_d97",
			"hms_bulwark_r08",
			"hms_campania_1914",
			"hms_campania_d48",
			"hms_chaser_d32",
			"hms_colossus_r15",
			"hms_courageous_50",
			"hms_dasher_d37",
			"hms_eagle_1918",
			"hms_eagle_r05",
			"hms_emperor_d98",
			"hms_empress_d42",
			"hms_fencer_d64",
			"hms_formidable_67",
			"hms_furious_47",
			"hms_glory_r62",
			"hms_hermes_95",
			"hms_hermes_r12",
			"hms_illustrious_87",
			"hms_illustrious_r06",
			"hms_implacable_r86",
			"hms_indefatigable_r10",
			"hms_indomitable_92",
			"hms_invincible_r05",
			"hms_khedive_d62",
			"hms_m2",
			"hms_manxman_1916",
			"hms_nabob_d77",
			"hms_nairana_1917",
			"hms_nairana_d05",
			"hms_ocean_l12",
			"hms_ocean_r68",
			"hms_patroller_d07",
			"hms_pegasus_1917",
			"hms_powerful_r95",
			"hms_premier_d23",
			"hms_prince_of_wales_r09",
			"hms_puncher_d79",
			"hms_pursuer_d73",
			"hms_queen_d19",
			"hms_queen_elizabeth_r08",
			"hms_rajah_d10",
			"hms_ranee_d03",
			"hms_ravager_d70",
			"hms_ruler_d72",
			"hms_searcher_d40",
			"hms_shah_d21",
			"hms_slinger_d26",
			"hms_smiter_d55",
			"hms_speaker_d90",
			"hms_stalker_d91",
			"hms_striker_d12",
			"hms_terrible_r93",
			"hms_tracker_d24",
			"hms_trouncer_d85",
			"hms_trumpeter_d09",
			"hms_unicorn_i72",
			"hms_venerable_r63",
			"hms_vengeance_r71",
			"hms_victorious_r38",
			"hms_vindex_1915",
			"hms_vindex_d15",
			"hms_warrior_r31",
			"hnlms_karel_doorman_qh1",
			"hnlms_karel_doorman_r81",
			"hswms_dristigheten",
			"hswms_gotland_1933",
			"htms_chakri_naruebet",
			"ins_vikramaditya",
			"ins_vikrant_2013",
			"ins_vikrant",
			"ins_viraat",
			"italian_aircraft_carrier_aquila",
			"italian_aircraft_carrier_cavour_550",
			"italian_aircraft_carrier_giuseppe_garibaldi_551",
			"italian_aircraft_carrier_sparviero",
			"japanese_aircraft_carrier_akagi",
			"japanese_aircraft_carrier_akitsu_maru",
			"japanese_aircraft_carrier_aso",
			"japanese_aircraft_carrier_chitose",
			"japanese_aircraft_carrier_chuyo",
			"japanese_aircraft_carrier_hiryu",
			"japanese_aircraft_carrier_hosho",
			"japanese_aircraft_carrier_ikoma",
			"japanese_aircraft_carrier_junyo",
			"japanese_aircraft_carrier_kaga",
			"japanese_aircraft_carrier_kaiyo",
			"japanese_aircraft_carrier_kasagi",
			"japanese_aircraft_carrier_katsuragi",
			"japanese_aircraft_carrier_kumano_maru",
			"japanese_aircraft_carrier_ryuho",
			"japanese_aircraft_carrier_ryujo",
			"japanese_aircraft_carrier_shimane_maru",
			"japanese_aircraft_carrier_shinyo",
			"japanese_aircraft_carrier_shoho",
			"japanese_aircraft_carrier_shokaku",
			"japanese_aircraft_carrier_soryu",
			"japanese_aircraft_carrier_taiho",
			"japanese_aircraft_carrier_taiyo",
			"japanese_aircraft_carrier_unryu",
			"japanese_aircraft_carrier_unyo",
			"japanese_aircraft_carrier_yamashiro_maru",
			"japanese_aircraft_carrier_zuiho",
			"japanese_aircraft_carrier_zuikaku",
			"japanese_battlecruiser_amagi",
			"japanese_battleship_hyuga",
			"japanese_submarine_i13",
			"japanese_submarine_i14",
			"japanese_submarine_i15",
			"japanese_submarine_i17",
			"japanese_submarine_i19",
			"japanese_submarine_i21",
			"japanese_submarine_i23",
			"japanese_submarine_i25",
			"japanese_submarine_i26",
			"japanese_submarine_i27",
			"japanese_submarine_i28",
			"japanese_submarine_i29",
			"japanese_submarine_i30",
			"japanese_submarine_i31",
			"japanese_submarine_i34",
			"japanese_submarine_i400",
			"japanese_submarine_i401",
			"jds_izumo_ddh183",
			"mv_alexia",
			"mv_ancylus",
			"mv_empire_macalpine",
			"mv_empire_macandrew",
			"mv_empire_maccoll",
			"mv_empire_macrae",
			"mv_rapana",
			"russian_aircraft_carrier_admiral_of_the_fleet_of_the_soviet_union_kuznetsov",
			"soviet_aircraft_carrier_admiral_gorshkov",
			"soviet_aircraft_carrier_admiral_of_the_fleet_of_the_soviet_union_kuznetsov",
			"soviet_aircraft_carrier_kiev",
			"soviet_aircraft_carrier_minsk",
			"soviet_aircraft_carrier_novorossiysk",
			"soviet_aircraft_carrier_varyag",
			"soviet_helicopter_carrier_leningrad",
			"soviet_helicopter_carrier_moskva",
			"spanish_aircraft_carrier_dedalo",
			"spanish_aircraft_carrier_principe_de_asturias",
			"spanish_seaplane_carrier_dedalo",
			"spanish_ship_juan_carlos_i_l61",
			"ss_europa_1928",
			"uss_admiralty_islands_cve99",
			"uss_altamaha_cve18",
			"uss_altamaha_cve6",
			"uss_america_cv66",
			"uss_antietam_cv36",
			"uss_anzio_cve57",
			"uss_archer_bavg1",
			"uss_attu_cve102",
			"uss_badoeng_strait_cve116",
			"uss_baffins_cve35",
			"uss_bairoko_cve115",
			"uss_barnes_cve20",
			"uss_barnes_cve7",
			"uss_bastian_cve37",
			"uss_bataan_cvl29",
			"uss_belleau_wood_cvl24",
			"uss_bennington_cv20",
			"uss_bismarck_sea_cve95",
			"uss_block_island_cve106",
			"uss_block_island_cve21",
			"uss_bogue_cve9",
			"uss_bolinas_cve36",
			"uss_bon_homme_richard_cv31",
			"uss_bougainville_cve100",
			"uss_boxer_cv21",
			"uss_breton_cve10",
			"uss_breton_cve23",
			"uss_bunker_hill_cv17",
			"uss_cabot_cvl28",
			"uss_cape_esperance_cve88",
			"uss_card_cve11",
			"uss_carl_vinson_cvn70",
			"uss_carnegie_cve38",
			"uss_casablanca_cve55",
			"uss_charger_cve30",
			"uss_chatham_cve32",
			"uss_chenango_cve28",
			"uss_constellation_cv64",
			"uss_copahee_cve12",
			"uss_coral_sea_cv43",
			"uss_cordova_cve39",
			"uss_core_cve13",
			"uss_corregidor_cve58",
			"uss_cowpens_cvl25",
			"uss_croatan_cve14",
			"uss_croatan_cve25",
			"uss_delgada_cve40",
			"uss_dwight_d_eisenhower_cvn69",
			"uss_edisto_cve41",
			"uss_enterprise_cv6",
			"uss_enterprise_cvn65",
			"uss_enterprise_cvn80",
			"uss_essex_cv9",
			"uss_estero_cve42",
			"uss_fanshaw_bay_cve70",
			"uss_forrestal_cv59",
			"uss_franklin_cv13",
			"uss_franklin_d_roosevelt_cv42",
			"uss_gambier_bay_cve73",
			"uss_george_hw_bush_cvn77",
			"uss_george_washington_cvn73",
			"uss_gerald_r_ford_cvn78",
			"uss_gilbert_islands_cve107",
			"uss_glacier_cve33",
			"uss_guadalcanal_cve60",
			"uss_hamlin_cve15",
			"uss_hancock_cv19",
			"uss_harry_s_truman_cvn75",
			"uss_hoggatt_bay_cve75",
			"uss_hollandia_cve97",
			"uss_hornet_cv12",
			"uss_hornet_cv8",
			"uss_independence_cv62",
			"uss_independence_cvl22",
			"uss_intrepid_cv11",
			"uss_iwo_jima_cv46",
			"uss_jamaica_cve43",
			"uss_john_c_stennis_cvn74",
			"uss_john_f_kennedy_cv67",
			"uss_john_f_kennedy_cvn79",
			"uss_kadashan_bay_cve76",
			"uss_kalinin_bay_cve68",
			"uss_kasaan_bay_cve69",
			"uss_kearsarge_cv33",
			"uss_keweenaw_cve44",
			"uss_kitkun_bay_cve71",
			"uss_kitty_hawk_cv63",
			"uss_kula_gulf_cve108",
			"uss_kwajalein_cve98",
			"uss_lake_champlain_cv39",
			"uss_langley_cv1",
			"uss_langley_cv27",
			"uss_lexington_cv16",
			"uss_lexington_cv2",
			"uss_leyte_cv32",
			"uss_liscome_bay_cve56",
			"uss_long_island_cve1",
			"uss_lst16",
			"uss_lst525",
			"uss_lst906",
			"uss_lunga_point_cve94",
			"uss_makassar_strait_cve91",
			"uss_makin_island_cve93",
			"uss_marcus_island_cve77",
			"uss_matanikau_cve101",
			"uss_midway_cv41",
			"uss_midway_cve63",
			"uss_mindoro_cve120",
			"uss_mission_bay_cve59",
			"uss_monterey_cv26",
			"uss_munda_cve104",
			"uss_nassau_cve16",
			"uss_natoma_bay_cve62",
			"uss_nehenta_bay_cve74",
			"uss_niantic_cve46",
			"uss_nimitz_cvn68",
			"uss_ommaney_bay_cve79",
			"uss_oriskany_cv34",
			"uss_palau_cve122",
			"uss_perdido_cve47",
			"uss_petrof_bay_cve80",
			"uss_philippine_sea_cv47",
			"uss_point_cruz_cve119",
			"uss_prince_cve45",
			"uss_princeton_cv37",
			"uss_princeton_cvl23",
			"uss_prince_william_cve19",
			"uss_prince_william_cve31",
			"uss_puget_sound_cve113",
			"uss_pybus_cve34",
			"uss_rabaul_cve121",
			"uss_randolph_cv15",
			"uss_ranger_cv4",
			"uss_ranger_cv61",
			"uss_rendova_cve114",
			"uss_reprisal_cv35",
			"uss_roi_cve103",
			"uss_ronald_reagan_cvn76",
			"uss_rudyerd_bay_cve81",
			"uss_sable_ix81",
			"uss_saginaw_bay_cve82",
			"uss_saidor_cve117",
			"uss_saipan_cvl48",
			"uss_salamaua_cve96",
			"uss_salerno_bay_cve110",
			"uss_sangamon_cve26",
			"uss_san_jacinto_cvl30",
			"uss_santee_cve29",
			"uss_saratoga_cv3",
			"uss_saratoga_cv60",
			"uss_sargent_bay_cve83",
			"uss_savo_island_cve78",
			"uss_shamrock_bay_cve84",
			"uss_shangrila_cv38",
			"uss_shipley_bay_cve85",
			"uss_siboney_cve112",
			"uss_sicily_cve118",
			"uss_sitkoh_bay_cve86",
			"uss_solomons_cve67",
			"uss_st_andrews_cve49",
			"uss_steamer_bay_cve87",
			"uss_st_george_cve17",
			"uss_st_joseph_cve50",
			"uss_st_lo_cve63",
			"uss_st_simon_cve51",
			"uss_suwannee_cve27",
			"uss_takanis_bay_cve89",
			"uss_tarawa_cv40",
			"uss_theodore_roosevelt_cvn71",
			"uss_thetis_bay_cve90",
			"uss_ticonderoga_cv14",
			"uss_tinian_cve123",
			"uss_tripoli_cve64",
			"uss_tulagi_cve72",
			"uss_united_states_cv58",
			"uss_valley_forge_cv45",
			"uss_vella_gulf_cve111",
			"uss_vermillion_cve52",
			"uss_wake_island_cve65",
			"uss_wasp_cv18",
			"uss_wasp_cv7",
			"uss_white_plains_cve66",
			"uss_willapa_cve53",
			"uss_windham_bay_cve92",
			"uss_wolverine_ix64",
			"uss_wright_cvl49",
			"uss_yorktown_cv10",
			"uss_yorktown_cv5",
			"carrier"
		};
	
	Integer[] imageIDs = {
			R.drawable.uss_harry_s_truman_cvn75_in_drydock_2012,
			R.drawable.ford,
			R.drawable.liaoning,
			R.drawable.kuznetsov,
			R.drawable.queenelizabeth,
			R.drawable.vikramaditya,
			R.drawable.charlesdegaulle,
			R.drawable.saopaulo,
			R.drawable.america,
			R.drawable.cavour,
			R.drawable.juancarlos,
			R.drawable.hyuga,
			R.drawable.chakrinaruebet,
			R.drawable.a12__cvn76,
			R.drawable.a4ku_landing_on_carrier_sao_paulo_2003,
			R.drawable.admiral_hipper_oni,
			R.drawable.aircraft_carrier_sao_paulo_in_rio_122007,
			R.drawable.aircraft_carriers_under_attack_at_kure_19_march_1945,
			R.drawable.baku_dnsc9005958r,
			R.drawable.baku_dnsn8906990c,
			R.drawable.benmychree_iii_on_her_sea_trials,
			R.drawable.bundesarchiv_bild_10207567_hamburg_brennende_europa_im_hafen,
			R.drawable.bundesarchiv_bild_10210309_katapultflugzeug_des_dampfers_europa,
			R.drawable.bundesarchiv_bild_134b0676_flugzeugtrager_graf_zeppelin,
			R.drawable.bundesarchiv_rm_25_bild02_flugzeugtrager_graf_zeppelin_bau,
			R.drawable.bundesarchiv_rm_25_bild64_flugzeugtrager_graf_zeppelin_bau,
			R.drawable.carrier_shokaku,
			R.drawable.cvn_73_gnangarra_02,
			R.drawable.dmitry_medvedev_on_the_admiral_kuznetsov,
			R.drawable.fig_of_japanese_aircraft_carrier_shoho_in_1942,
			R.drawable.grafzeppelin1,
			R.drawable.hms_benmychree_off_the_dardanelles,
			R.drawable.hms_benmychree_underfire_11_january_1917,
			R.drawable.hms_ocean_ifos2005_cropped,
			R.drawable.hms_ocean_moored_in_greenwich_london_for_the_2012_olympic_games,
			R.drawable.ijn_carrier_amagi_capsized_off_kure_in_1946,
			R.drawable.indian_navy_flotilla_with_aircraft_carriers_vikramaditya_r33_and_viraat_r22,
			R.drawable.ins_vikramaditya_in_baltic_sea,
			R.drawable.ins_vikrant_cgi,
			R.drawable.japanese_aircraft_carrier_kasagi_cropped,
			R.drawable.japanese_aircraft_carrier_zuiho,
			R.drawable.js_izumo_ddh183_just_after_her_launch,
			R.drawable.juan_carlos_l61_in_istanbul,
			R.drawable.katsuragi_awm_099798,
			R.drawable.la_foudre,
			R.drawable.la_foudre_tending_torpedo_boats_bf_1923,
			R.drawable.launch_of_benmychree_iii_march_23rd_1908,
			R.drawable.lhd_juan_carlos_i_in_malaga,
			R.drawable.lowering_the_flag_on_zuikaku,
			R.drawable.mikoyan_mig29k_of_the_indian_navy,
			R.drawable.qe_class_carrier,
			R.drawable.seydlitz_reconnaissance_photo,
			R.drawable.shoho_g17026,
			R.drawable.shoho_under_attack,
			R.drawable.shokaku_prelaunch,
			R.drawable.shokaku_santa_cruz_fire,
			R.drawable.ss_europa_ss_paris_sank,
			R.drawable.ss_liberte,
			R.drawable.statelibqld_1_133753_benmycaree_ship,
			R.drawable.stern_of_hms_benmychree,
			R.drawable.tbf_georgebush,
			R.drawable.torpedoe_boat_tender_foudre,
			R.drawable.uss_gerald_r_ford_cvn78_in_dry_dock_front_view_2013,
			R.drawable.uss_harry_s_truman_cvn75_in_drydock_2012,
			R.drawable.uss_john_c_stennis_cvn74__hms_illustrious_r_06,
			R.drawable.uss_reagan071030n6074y053,
			R.drawable.ussronaldreaganbyphilkonstantin,
			R.drawable.varyag_during_refitting,
			R.drawable.vikramaditya_7,
			R.drawable.vikrant,
			R.drawable.zuiho1944,
			R.drawable.zuikaku_at_cape_engano,
			R.drawable.zuikaku_flight_deck,
			R.drawable.zuikaku_november_1941,
			R.drawable.uss_abraham_lincoln_cvn_72,
			R.drawable.japanese_battlecruiser_amagi,
			R.drawable.ara_independencia_1958,
			R.drawable.ara_veinticinco_de_mayo_v2,
			R.drawable.brazilian_aircraft_carrier_minas_gerais,
			R.drawable.brazilian_aircraft_carrier_sao_paulo_a12,
			R.drawable.chinese_aircraft_carrier_liaoning,
			R.drawable.flugzeugtrager_b,
			R.drawable.french_aircraft_carrier_arromanches_r95,
			R.drawable.french_aircraft_carrier_bearn,
			R.drawable.french_aircraft_carrier_bois_belleau,
			R.drawable.french_aircraft_carrier_charles_de_gaulle_r91,
			R.drawable.french_aircraft_carrier_charles_de_gaulle_r91,
			R.drawable.french_aircraft_carrier_clemenceau_r98,
			R.drawable.french_aircraft_carrier_dixmude,
			R.drawable.french_aircraft_carrier_foch_r99,
			R.drawable.french_aircraft_carrier_joffre,
			R.drawable.french_aircraft_carrier_la_fayette_r96,
			R.drawable.french_aircraft_carrier_painleve,
			R.drawable.french_aircraft_carrier_verdun,
			R.drawable.french_seaplane_carrier_commandant_teste,
			R.drawable.french_seaplane_carrier_foudre,
			R.drawable.french_submarine_surcouf,
			R.drawable.german_aircraft_carrier_graf_zeppelin,
			R.drawable.german_cruiser_seydlitz,
			R.drawable.hmas_albatross_1928,
			R.drawable.hmas_melbourne_r21,
			R.drawable.hmas_sydney_r17,
			R.drawable.hmas_vengeance_r71,
			R.drawable.hmcs_bonaventure_cvl_22,
			R.drawable.hmcs_magnificent_cvl21,
			R.drawable.hmcs_warrior_r31,
			R.drawable.hms_activity_d94,
			R.drawable.hms_albion_r07,
			R.drawable.hms_ameer_d01,
			R.drawable.hms_arbiter_d31,
			R.drawable.hms_archer_d78,
			R.drawable.hms_argus_i49,
			R.drawable.hms_ark_royal_1914,
			R.drawable.hms_ark_royal_91,
			R.drawable.hms_ark_royal_r07,
			R.drawable.hms_ark_royal_r09,
			R.drawable.hms_atheling_d51,
			R.drawable.hms_attacker_d02,
			R.drawable.hms_audacity_d10,
			R.drawable.hms_avenger_d14,
			R.drawable.hms_battler_d18,
			R.drawable.hms_begum_d38,
			R.drawable.hms_benmychree,
			R.drawable.hms_biter_d97,
			R.drawable.hms_bulwark_r08,
			R.drawable.hms_campania_1914,
			R.drawable.hms_campania_d48,
			R.drawable.hms_chaser_d32,
			R.drawable.hms_colossus_r15,
			R.drawable.hms_courageous_50,
			R.drawable.hms_dasher_d37,
			R.drawable.hms_eagle_1918,
			R.drawable.hms_eagle_r05,
			R.drawable.hms_emperor_d98,
			R.drawable.hms_empress_d42,
			R.drawable.hms_fencer_d64,
			R.drawable.hms_formidable_67,
			R.drawable.hms_furious_47,
			R.drawable.hms_glory_r62,
			R.drawable.hms_hermes_95,
			R.drawable.hms_hermes_r12,
			R.drawable.hms_illustrious_87,
			R.drawable.hms_illustrious_r06,
			R.drawable.hms_implacable_r86,
			R.drawable.hms_indefatigable_r10,
			R.drawable.hms_indomitable_92,
			R.drawable.hms_invincible_r05,
			R.drawable.hms_khedive_d62,
			R.drawable.hms_m2,
			R.drawable.hms_manxman_1916,
			R.drawable.hms_nabob_d77,
			R.drawable.hms_nairana_1917,
			R.drawable.hms_nairana_d05,
			R.drawable.hms_ocean_l12,
			R.drawable.hms_ocean_r68,
			R.drawable.hms_patroller_d07,
			R.drawable.hms_pegasus_1917,
			R.drawable.hms_powerful_r95,
			R.drawable.hms_premier_d23,
			R.drawable.hms_prince_of_wales_r09,
			R.drawable.hms_puncher_d79,
			R.drawable.hms_pursuer_d73,
			R.drawable.hms_queen_d19,
			R.drawable.hms_queen_elizabeth_r08,
			R.drawable.hms_rajah_d10,
			R.drawable.hms_ranee_d03,
			R.drawable.hms_ravager_d70,
			R.drawable.hms_ruler_d72,
			R.drawable.hms_searcher_d40,
			R.drawable.hms_shah_d21,
			R.drawable.hms_slinger_d26,
			R.drawable.hms_smiter_d55,
			R.drawable.hms_speaker_d90,
			R.drawable.hms_stalker_d91,
			R.drawable.hms_striker_d12,
			R.drawable.hms_terrible_r93,
			R.drawable.hms_tracker_d24,
			R.drawable.hms_trouncer_d85,
			R.drawable.hms_trumpeter_d09,
			R.drawable.hms_unicorn_i72,
			R.drawable.hms_venerable_r63,
			R.drawable.hms_vengeance_r71,
			R.drawable.hms_victorious_r38,
			R.drawable.hms_vindex_1915,
			R.drawable.hms_vindex_d15,
			R.drawable.hms_warrior_r31,
			R.drawable.hnlms_karel_doorman_qh1,
			R.drawable.hnlms_karel_doorman_r81,
			R.drawable.hswms_dristigheten,
			R.drawable.hswms_gotland_1933,
			R.drawable.htms_chakri_naruebet,
			R.drawable.ins_vikramaditya,
			R.drawable.ins_vikrant_2013,
			R.drawable.ins_vikrant,
			R.drawable.ins_viraat,
			R.drawable.italian_aircraft_carrier_aquila,
			R.drawable.italian_aircraft_carrier_cavour_550,
			R.drawable.italian_aircraft_carrier_giuseppe_garibaldi_551,
			R.drawable.italian_aircraft_carrier_sparviero,
			R.drawable.japanese_aircraft_carrier_akagi,
			R.drawable.japanese_aircraft_carrier_akitsu_maru,
			R.drawable.japanese_aircraft_carrier_aso,
			R.drawable.japanese_aircraft_carrier_chitose,
			R.drawable.japanese_aircraft_carrier_chuyo,
			R.drawable.japanese_aircraft_carrier_hiryu,
			R.drawable.japanese_aircraft_carrier_hosho,
			R.drawable.japanese_aircraft_carrier_ikoma,
			R.drawable.japanese_aircraft_carrier_junyo,
			R.drawable.japanese_aircraft_carrier_kaga,
			R.drawable.japanese_aircraft_carrier_kaiyo,
			R.drawable.japanese_aircraft_carrier_kasagi,
			R.drawable.japanese_aircraft_carrier_katsuragi,
			R.drawable.japanese_aircraft_carrier_kumano_maru,
			R.drawable.japanese_aircraft_carrier_ryuho,
			R.drawable.japanese_aircraft_carrier_ryujo,
			R.drawable.japanese_aircraft_carrier_shimane_maru,
			R.drawable.japanese_aircraft_carrier_shinyo,
			R.drawable.japanese_aircraft_carrier_shoho,
			R.drawable.japanese_aircraft_carrier_shokaku,
			R.drawable.japanese_aircraft_carrier_soryu,
			R.drawable.japanese_aircraft_carrier_taiho,
			R.drawable.japanese_aircraft_carrier_taiyo,
			R.drawable.japanese_aircraft_carrier_unryu,
			R.drawable.japanese_aircraft_carrier_unyo,
			R.drawable.japanese_aircraft_carrier_yamashiro_maru,
			R.drawable.japanese_aircraft_carrier_zuiho,
			R.drawable.japanese_aircraft_carrier_zuikaku,
			R.drawable.japanese_battlecruiser_amagi,
			R.drawable.japanese_battleship_hyuga,
			R.drawable.japanese_submarine_i13,
			R.drawable.japanese_submarine_i14,
			R.drawable.japanese_submarine_i15,
			R.drawable.japanese_submarine_i17,
			R.drawable.japanese_submarine_i19,
			R.drawable.japanese_submarine_i21,
			R.drawable.japanese_submarine_i23,
			R.drawable.japanese_submarine_i25,
			R.drawable.japanese_submarine_i26,
			R.drawable.japanese_submarine_i27,
			R.drawable.japanese_submarine_i28,
			R.drawable.japanese_submarine_i29,
			R.drawable.japanese_submarine_i30,
			R.drawable.japanese_submarine_i31,
			R.drawable.japanese_submarine_i34,
			R.drawable.japanese_submarine_i400,
			R.drawable.japanese_submarine_i401,
			R.drawable.jds_izumo_ddh183,
			R.drawable.mv_alexia,
			R.drawable.mv_ancylus,
			R.drawable.mv_empire_macalpine,
			R.drawable.mv_empire_macandrew,
			R.drawable.mv_empire_maccoll,
			R.drawable.mv_empire_macrae,
			R.drawable.mv_rapana,
			R.drawable.russian_aircraft_carrier_admiral_of_the_fleet_of_the_soviet_union_kuznetsov,
			R.drawable.soviet_aircraft_carrier_admiral_gorshkov,
			R.drawable.soviet_aircraft_carrier_admiral_of_the_fleet_of_the_soviet_union_kuznetsov,
			R.drawable.soviet_aircraft_carrier_kiev,
			R.drawable.soviet_aircraft_carrier_minsk,
			R.drawable.soviet_aircraft_carrier_novorossiysk,
			R.drawable.soviet_aircraft_carrier_varyag,
			R.drawable.soviet_helicopter_carrier_leningrad,
			R.drawable.soviet_helicopter_carrier_moskva,
			R.drawable.spanish_aircraft_carrier_dedalo,
			R.drawable.spanish_aircraft_carrier_principe_de_asturias,
			R.drawable.spanish_seaplane_carrier_dedalo,
			R.drawable.spanish_ship_juan_carlos_i_l61,
			R.drawable.ss_europa_1928, R.drawable.uss_admiralty_islands_cve99,
			R.drawable.uss_altamaha_cve18, R.drawable.uss_altamaha_cve6,
			R.drawable.uss_america_cv66, R.drawable.uss_antietam_cv36,
			R.drawable.uss_anzio_cve57, R.drawable.uss_archer_bavg1,
			R.drawable.uss_attu_cve102, R.drawable.uss_badoeng_strait_cve116,
			R.drawable.uss_baffins_cve35, R.drawable.uss_bairoko_cve115,
			R.drawable.uss_barnes_cve20, R.drawable.uss_barnes_cve7,
			R.drawable.uss_bastian_cve37, R.drawable.uss_bataan_cvl29,
			R.drawable.uss_belleau_wood_cvl24, R.drawable.uss_bennington_cv20,
			R.drawable.uss_bismarck_sea_cve95,
			R.drawable.uss_block_island_cve106,
			R.drawable.uss_block_island_cve21, R.drawable.uss_bogue_cve9,
			R.drawable.uss_bolinas_cve36,
			R.drawable.uss_bon_homme_richard_cv31,
			R.drawable.uss_bougainville_cve100, R.drawable.uss_boxer_cv21,
			R.drawable.uss_breton_cve10, R.drawable.uss_breton_cve23,
			R.drawable.uss_bunker_hill_cv17, R.drawable.uss_cabot_cvl28,
			R.drawable.uss_cape_esperance_cve88, R.drawable.uss_card_cve11,
			R.drawable.uss_carl_vinson_cvn70, R.drawable.uss_carnegie_cve38,
			R.drawable.uss_casablanca_cve55, R.drawable.uss_charger_cve30,
			R.drawable.uss_chatham_cve32, R.drawable.uss_chenango_cve28,
			R.drawable.uss_constellation_cv64, R.drawable.uss_copahee_cve12,
			R.drawable.uss_coral_sea_cv43, R.drawable.uss_cordova_cve39,
			R.drawable.uss_core_cve13, R.drawable.uss_corregidor_cve58,
			R.drawable.uss_cowpens_cvl25, R.drawable.uss_croatan_cve14,
			R.drawable.uss_croatan_cve25, R.drawable.uss_delgada_cve40,
			R.drawable.uss_dwight_d_eisenhower_cvn69,
			R.drawable.uss_edisto_cve41, R.drawable.uss_enterprise_cv6,
			R.drawable.uss_enterprise_cvn65, R.drawable.uss_enterprise_cvn80,
			R.drawable.uss_essex_cv9, R.drawable.uss_estero_cve42,
			R.drawable.uss_fanshaw_bay_cve70, R.drawable.uss_forrestal_cv59,
			R.drawable.uss_franklin_cv13,
			R.drawable.uss_franklin_d_roosevelt_cv42,
			R.drawable.uss_gambier_bay_cve73,
			R.drawable.uss_george_hw_bush_cvn77,
			R.drawable.uss_george_washington_cvn73,
			R.drawable.uss_gerald_r_ford_cvn78,
			R.drawable.uss_gilbert_islands_cve107,
			R.drawable.uss_glacier_cve33, R.drawable.uss_guadalcanal_cve60,
			R.drawable.uss_hamlin_cve15, R.drawable.uss_hancock_cv19,
			R.drawable.uss_harry_s_truman_cvn75,
			R.drawable.uss_hoggatt_bay_cve75, R.drawable.uss_hollandia_cve97,
			R.drawable.uss_hornet_cv12, R.drawable.uss_hornet_cv8,
			R.drawable.uss_independence_cv62,
			R.drawable.uss_independence_cvl22, R.drawable.uss_intrepid_cv11,
			R.drawable.uss_iwo_jima_cv46, R.drawable.uss_jamaica_cve43,
			R.drawable.uss_john_c_stennis_cvn74,
			R.drawable.uss_john_f_kennedy_cv67,
			R.drawable.uss_john_f_kennedy_cvn79,
			R.drawable.uss_kadashan_bay_cve76,
			R.drawable.uss_kalinin_bay_cve68, R.drawable.uss_kasaan_bay_cve69,
			R.drawable.uss_kearsarge_cv33, R.drawable.uss_keweenaw_cve44,
			R.drawable.uss_kitkun_bay_cve71, R.drawable.uss_kitty_hawk_cv63,
			R.drawable.uss_kula_gulf_cve108, R.drawable.uss_kwajalein_cve98,
			R.drawable.uss_lake_champlain_cv39, R.drawable.uss_langley_cv1,
			R.drawable.uss_langley_cv27, R.drawable.uss_lexington_cv16,
			R.drawable.uss_lexington_cv2, R.drawable.uss_leyte_cv32,
			R.drawable.uss_liscome_bay_cve56, R.drawable.uss_long_island_cve1,
			R.drawable.uss_lst16, R.drawable.uss_lst525, R.drawable.uss_lst906,
			R.drawable.uss_lunga_point_cve94,
			R.drawable.uss_makassar_strait_cve91,
			R.drawable.uss_makin_island_cve93,
			R.drawable.uss_marcus_island_cve77,
			R.drawable.uss_matanikau_cve101, R.drawable.uss_midway_cv41,
			R.drawable.uss_midway_cve63, R.drawable.uss_mindoro_cve120,
			R.drawable.uss_mission_bay_cve59, R.drawable.uss_monterey_cv26,
			R.drawable.uss_munda_cve104, R.drawable.uss_nassau_cve16,
			R.drawable.uss_natoma_bay_cve62, R.drawable.uss_nehenta_bay_cve74,
			R.drawable.uss_niantic_cve46, R.drawable.uss_nimitz_cvn68,
			R.drawable.uss_ommaney_bay_cve79, R.drawable.uss_oriskany_cv34,
			R.drawable.uss_palau_cve122, R.drawable.uss_perdido_cve47,
			R.drawable.uss_petrof_bay_cve80,
			R.drawable.uss_philippine_sea_cv47,
			R.drawable.uss_point_cruz_cve119, R.drawable.uss_prince_cve45,
			R.drawable.uss_princeton_cv37, R.drawable.uss_princeton_cvl23,
			R.drawable.uss_prince_william_cve19,
			R.drawable.uss_prince_william_cve31,
			R.drawable.uss_puget_sound_cve113, R.drawable.uss_pybus_cve34,
			R.drawable.uss_rabaul_cve121, R.drawable.uss_randolph_cv15,
			R.drawable.uss_ranger_cv4, R.drawable.uss_ranger_cv61,
			R.drawable.uss_rendova_cve114, R.drawable.uss_reprisal_cv35,
			R.drawable.uss_roi_cve103, R.drawable.uss_ronald_reagan_cvn76,
			R.drawable.uss_rudyerd_bay_cve81, R.drawable.uss_sable_ix81,
			R.drawable.uss_saginaw_bay_cve82, R.drawable.uss_saidor_cve117,
			R.drawable.uss_saipan_cvl48, R.drawable.uss_salamaua_cve96,
			R.drawable.uss_salerno_bay_cve110, R.drawable.uss_sangamon_cve26,
			R.drawable.uss_san_jacinto_cvl30, R.drawable.uss_santee_cve29,
			R.drawable.uss_saratoga_cv3, R.drawable.uss_saratoga_cv60,
			R.drawable.uss_sargent_bay_cve83, R.drawable.uss_savo_island_cve78,
			R.drawable.uss_shamrock_bay_cve84, R.drawable.uss_shangrila_cv38,
			R.drawable.uss_shipley_bay_cve85, R.drawable.uss_siboney_cve112,
			R.drawable.uss_sicily_cve118, R.drawable.uss_sitkoh_bay_cve86,
			R.drawable.uss_solomons_cve67, R.drawable.uss_st_andrews_cve49,
			R.drawable.uss_steamer_bay_cve87, R.drawable.uss_st_george_cve17,
			R.drawable.uss_st_joseph_cve50, R.drawable.uss_st_lo_cve63,
			R.drawable.uss_st_simon_cve51, R.drawable.uss_suwannee_cve27,
			R.drawable.uss_takanis_bay_cve89, R.drawable.uss_tarawa_cv40,
			R.drawable.uss_theodore_roosevelt_cvn71,
			R.drawable.uss_thetis_bay_cve90, R.drawable.uss_ticonderoga_cv14,
			R.drawable.uss_tinian_cve123, R.drawable.uss_tripoli_cve64,
			R.drawable.uss_tulagi_cve72, R.drawable.uss_united_states_cv58,
			R.drawable.uss_valley_forge_cv45, R.drawable.uss_vella_gulf_cve111,
			R.drawable.uss_vermillion_cve52, R.drawable.uss_wake_island_cve65,
			R.drawable.uss_wasp_cv18, R.drawable.uss_wasp_cv7,
			R.drawable.uss_white_plains_cve66, R.drawable.uss_willapa_cve53,
			R.drawable.uss_windham_bay_cve92, R.drawable.uss_wolverine_ix64,
			R.drawable.uss_wright_cvl49, R.drawable.uss_yorktown_cv10,
			R.drawable.uss_yorktown_cv5, R.drawable.carrier };

	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_pictures);
		//ImageView iv = (ImageView) findViewById(R.id.image1);
		//iv.setImageResource(imageIDs[index]);
		//TextView tv = (TextView) findViewById(R.id.txt_Aircraftcarriername);
		//tv.setText(stringCarriers[index]);
		//stringCarriers/imageIDs
		com.jimsuplee.aircraftcarriers.Pictures.index = 0;
		displayTextAndImage();
	}
	public void displayTextAndImage() {
		ImageView iv = (ImageView) findViewById(R.id.image1);
		iv.setImageResource(imageIDs[com.jimsuplee.aircraftcarriers.Pictures.index]);
		TextView tv = (TextView) findViewById(R.id.txt_picture);
		String carrierText = stringCarriers[com.jimsuplee.aircraftcarriers.Pictures.index]+" ("+Integer.toString(com.jimsuplee.aircraftcarriers.Pictures.index)+" of 458)";
		//tv.setText(stringCarriers[com.jimsuplee.aircraftcarriers.Pictures.index]);
		tv.setText(carrierText);
	}
	public void onClickPicture(View view) {
		if(index<459) {
		    index+=1;
		}
		displayTextAndImage();
	}	
	public void onClickPictureback(View view) {
		if(index>0) {
			index-=1;
		}
		displayTextAndImage();
	}
}
